version: '3.8'

services:
  my-nginx-server-web-service:
    image: nginx:latest
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
    ports:
      - "80:80"
