name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Specify your Dockerfile path
          push: true
          platforms: linux/amd64,linux/arm64 # Add more platforms if needed
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/sum-nodejs-image:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/sum-nodejs-image:${{ github.sha }}
