name: NodeJS project 1 build and test

on:
  push:
    paths:
      - "node-js-1/**"
    branches:
      - main
  # workflow_dispatch:

jobs:
  subdirectory1-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./node-js-1/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run subdirectory1 workflow steps
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm test
