name: NodeJS project 1 build and test

on:
  push:
    paths:
      - "node-js-1/**"
    branches:
      - main

jobs:
  subdirectory1-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run subdirectory1 workflow steps
        run: |
          npm ci 
          npm test
