name: NodeJS project 2 build and test

on:
  push:
    paths:
      - "node-js-2/**"
    branches:
      - main
  workflow_dispatch: {}

jobs:
  subdirectory2-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./node-js-2/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run subdirectory2 workflow steps
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm ci
      - run: npm test
