name: Using my custom GitHub action

# on: [push]
on:
  # push:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Where Am I?
        run: ls -la

      - name: Debug /
        run: ls -la /

      - name: Debug env
        run: env

      - run: which sh # => /usr/bin/sh on GitHub action env
      - run: which bash # => /usr/bin/bash on GitHub action env

      - run: docker images

      - name: USING MY CUSTOM GITHUB ACTION
        uses: alundiak/devops-gha@main
        # https://github.com/alundiak/devops-gha

      - run: docker images
